### PR TITLE
document state is not updated when the mention is selected

### PR DESCRIPTION
**Pull request by ravi7mech**
Co-Authored-By: gdelory <9974707+gdelory@users.noreply.github.com>

### CODE REVIEW

**Comment by joelewis** [comment]
Hi, thanks for the patch! Can you quickly explain more about the issue. I tried in the demo editor running @ https://star-drug.glitch.me/ and the state does seems like it's updated when a mention is selected.

**Comment by gdelory** [comment]
Hi, I tried to simplified my sample in a codebox so you can see, and I also recorder my screen. This is ugly, I have no css whatsoever, but it should be enough for you to reproduce, it was for me.

Issue is that because the event is not properly dispatched, it doesn't correctly call `dispatchTransaction`, which react prosemirror relies on to trigger the change event (which we rely on to update our state and do stuff). 

As you can see on the gifs, every time I type, the `handleChange` is triggered, but *not* when I select a mention. As soon as I enter anything else, it does fix it, but issue is that our users usually put a mention at the end and save, and therefor we don't actually save the mention, just what they types so far

Here is the recording:
prosemirror-mention-issue-29

Here is the sandbox: https://codesandbox.io/s/holy-sun-k3vp2?file=/src/App.js:1369-1381

**Comment by joelewis** [comment]
Got it @gdelory 
Thanks for the live demo. Looks good to go :)

**Comment by gdelory** [comment]
awesome, thanks a lot for merging that fast 😃  Any idea when this will be released to npmjs.com? Or you're not planning to and we should install from git directly?

**Comment by gdelory** [comment]
@joelewis in case you didn't get a notification, if you had sorry for the spam 😉

**Comment by joelewis** [comment]
Hi @gdelory 
I'll pull together some time to publish it in npm this weekend. Will update here once once it's done?

**Comment by gdelory** [comment]
Awesome thanks a lot

**Comment by joelewis** [comment]
The latest version is published to npm now.

**Comment by gdelory** [comment]
Hi, unfortunately it seems like the change didn't make it to the compiled version in `dist/index.js` and `dist/index.es.js`, only in the source file. Not sure why though

See https://registry.npmjs.org/prosemirror-mentions/-/prosemirror-mentions-1.0.1.tgz

**Comment by joelewis** [comment]
Published with compiled versions in npm. Thanks for the heads up @gdelory I did forget to run the build script. I've fixed the rollup config as well.

**Comment by gdelory** [comment]
@joelewis Thank you so much for your reactivity! I know this is volunteer work so I'm really grateful for you answering and fixing things so quickly.

New version installed and deployed, original issue fixed, everything works like a charm 🎉 

Thank you!

**Pull request merged**
